version: '3.8'

services:
  main:
    container_name: service-unider-backend
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:debug
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
    networks:
      - service-unider-network
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: service-unider-database-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    networks:
      - service-unider-network
    volumes:
      - service-unider-database-postgres-volume:/data
    restart: unless-stopped

networks:
  service-unider-network:
    name: service-unider-network

volumes:
  service-unider-database-postgres-volume:
    name: service-unider-database-postgres-volume
